source 'https://rubygems.org'
ruby "2.2.3"
gem 'rails', '4.2.4'
# moved the gem 'sqlite3' from here down to group :development area
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem "paperclip", "~> 4.3"
gem "paperclip-dropbox", ">= 1.1.7"
# Added the above gem to allow image storage on drobox
gem "figaro"
gem 'sdoc', '~> 0.4.0', group: :doc
# gem 'carrierwave' # Added this gem to allow images in our app

group :production do
  gem 'rails_12factor'
end

group :production do
  gem 'pg'
end

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :development do
  gem 'sqlite3'
end
